---
title: "TODO"
author: "TODO"
date: "Abril, 2020"
output: pdf_document
---
```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(scales)
library(gridExtra)
library(stringr)
options(scipen=999)
```

```{r}
load_csv <- function(file_name){
  df <- read.csv(file_name)
  return(df)
}

get_data <- function(path_name){
  results_path = path_name
  gci_30s <- rbind(
    load_csv(paste(results_path, "sim-pp-gci30s1-normscheduler-instances.csv", sep=""))
  )
  gci_5m <- rbind(
    load_csv(paste(results_path, "sim-pp-gci5m1-normscheduler-instances.csv", sep=""))
  )
  gci_15m <- rbind(
    load_csv(paste(results_path, "sim-pp-gci15m1-normscheduler-instances.csv", sep=""))
  )
  gci_45m <- rbind(
    load_csv(paste(results_path, "sim-pp-gci45m1-normscheduler-instances.csv", sep=""))
  )
  gci_60m <- rbind(
    load_csv(paste(results_path, "sim-pp-gci60m1-normscheduler-instances.csv", sep=""))
  )
  
  nogci_30s <- rbind(
    load_csv(paste(results_path, "sim-pp-nogci30s1-normscheduler-instances.csv", sep=""))
  )
  nogci_5m <- rbind(
    load_csv(paste(results_path, "sim-pp-nogci5m1-normscheduler-instances.csv", sep=""))
  )
  nogci_15m <- rbind(
    load_csv(paste(results_path, "sim-pp-nogci15m1-normscheduler-instances.csv", sep=""))
  )
  nogci_45m <- rbind(
    load_csv(paste(results_path, "sim-pp-nogci45m1-normscheduler-instances.csv", sep=""))
  )
  nogci_60m <- rbind(
    load_csv(paste(results_path, "sim-pp-nogci60m1-normscheduler-instances.csv", sep=""))
  )
    
  idle_deadline = c(
    '30s', '5m', '15m', '45m', '60m',
    '30s', '5m', '15m', '45m', '60m'
  )
  type = c(
    'GCI', 'GCI', 'GCI', 'GCI', 'GCI', 'NOGCI', 'NOGCI', 'NOGCI', 'NOGCI', 'NOGCI'
  )
  idle_time = c(
    sum(gci_30s$idle_time), sum(gci_5m$idle_time), sum(gci_15m$idle_time), sum(gci_45m$idle_time), sum(gci_60m$idle_time),
    sum(nogci_30s$idle_time), sum(nogci_5m$idle_time), sum(nogci_15m$idle_time), sum(nogci_45m$idle_time), sum(nogci_60m$idle_time)
  )
  busy_time = c(
    sum(gci_30s$busyTime), sum(gci_5m$busyTime), sum(gci_15m$busyTime), sum(gci_45m$busyTime), sum(gci_60m$busyTime),
    sum(nogci_30s$busyTime), sum(nogci_5m$busyTime), sum(nogci_15m$busyTime), sum(nogci_45m$busyTime), sum(nogci_60m$busyTime)
  )
  efficiency = c(
    mean(gci_30s$efficiency), mean(gci_5m$efficiency), mean(gci_15m$efficiency), mean(gci_45m$efficiency), mean(gci_60m$efficiency),
    mean(nogci_30s$efficiency), mean(nogci_5m$efficiency), mean(nogci_15m$efficiency), mean(nogci_45m$efficiency), mean(nogci_60m$efficiency)
  )
  up_time = c(
    sum(gci_30s$up_time), sum(gci_5m$up_time), sum(gci_15m$up_time), sum(gci_45m$up_time), sum(gci_60m$up_time),
    sum(nogci_30s$up_time), sum(nogci_5m$up_time), sum(nogci_15m$up_time), sum(nogci_45m$up_time), sum(nogci_60m$up_time)
  )
  billing = 0.0000008333
  cost_to_user = busy_time * billing
  
  df = data.frame(idle_deadline, type, idle_time, busy_time, efficiency, up_time, cost_to_user)
  
  return(df)
}

```

```{r}
df = get_data("../simulation/results2h30m/")
print("Cost comparison between GCI and NOGCI")
ggplot(df, aes(fill=type, y=cost_to_user, x=factor(idle_deadline, level = c('30s', '5m', '15m', '45m', '60m')))) +
  geom_bar(positio="dodge", stat="identity", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  xlab("Idle Deadline Time") +
  ylab("Cost (in USD)") + ylim(0, 0.0125) +
  scale_fill_manual("type", values = c("GCI"="blue", "NOGCI"="red")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
    
print("Efficiency comparison between GCI and NOGCI")
ggplot(df, aes(fill=type, y=efficiency * 100, x=factor(idle_deadline, level = c('30s', '5m', '15m', '45m', '60m')))) +
  geom_bar(positio="dodge", stat="identity", width=0.5) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  xlab("Idle Deadline Time") +
  ylab("Efficiecy (in %)") +
  scale_fill_manual("type", values = c("GCI"="blue", "NOGCI"="red")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
```







